"""Add history tables

Revision ID: 864760f19b85
Revises: eaca851395fe
Create Date: 2025-12-12 07:33:16.526445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864760f19b85'
down_revision: Union[str, Sequence[str], None] = 'eaca851395fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('prediction', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_histories_created_at'), 'prediction_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_histories_id'), 'prediction_histories', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_histories_user_id'), 'prediction_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_histories_user_id'), table_name='prediction_histories')
    op.drop_index(op.f('ix_prediction_histories_id'), table_name='prediction_histories')
    op.drop_index(op.f('ix_prediction_histories_created_at'), table_name='prediction_histories')
    op.drop_table('prediction_histories')
    # ### end Alembic commands ###
